name: copilot
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13
  - ipykernel
  - conda-forge::nodejs
  - conda-forge::sqlite
prefix: /Users/ferdi/miniconda3/envs/copilot
