project_root: /Users/jub/agent-copilot/example_workflows/debug_examples/

# Should we cache request attachements so you can see it in the scratchpad?
request_attachments:
  cache_attachments: true
  cache_dir: /Users/jub/agent-copilot/attachment_cache