working_stage="./working_stage"
code_dir = "./rustdb"
llm="sonnet3.7-nothink"   # "gpt-4o", "sonnet", "sonnetv2", "sonnet3.7", "sonnet3.7-nothink", "o3-mini-high", "o3-mini-low", "o3-mini-medium"
low_complexity_llm="sonnet3.7-nothink"
use_openhands = false # Run OpenHands with the LLM defined in `llm`
verbose=false
testgen=true
max_llm_attempts=3
text_split_length=4096
autofix=false
target_language="py"
ignore_unit_test_error=true # if set to true, unit test error will be write to a .error file, otherwise the generation crushes when it cannot fix to pass a unit test
test_approved=false # after you manually approved all test cases, set it so that we do not re-generate test cases
compilation_attempts=2
default_system_msg = """
You are a programmer trying to fix Github issues. Be sure to format your responses correctly and to only include the necessary changes.
"""
confidence_approach='naive' # choose among ['', 'naive', 're-evaluate']
